apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-redis-auth
  namespace: workload
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-cluster-store
  target:
    name: nextcloud-redis-auth
    creationPolicy: Owner
  data:
    - secretKey: redis-password
      remoteRef:
        key: "op://5vr4hef2746tpplvjx424xafvu/nextcloud-main/nextcloud-redis"
