k3s_channel: "stable"

internal_cluster_control_plane_group: "ops_brain"
internal_cluster_worker_group: "platform_workers"
internal_cluster_server_port: "6443"

internal_cluster_node_labels:
  monitoring: "rita.role=ops-brain"
  platform: "rita.role=platform"
