apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-secrets
  namespace: platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: n8n-secrets
    creationPolicy: Owner
  data:
    - secretKey: db-password
      remoteRef:
        key: "n8n-secrets/db-password"
    - secretKey: encryption-key
      remoteRef:
        key: "n8n-secrets/encryption-key"
