apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-db-secret
  namespace: workload
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-cluster-store
  target:
    name: nextcloud-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        db-name: nextcloud
        db-user: nextcloud
        db-password: "{{ .db_password }}"
  data:
    - secretKey: db_password
      remoteRef:
        key: "nextcloud-main/nextcloud-db"
