apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-admin-secret
  namespace: workload
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-cluster-store
  target:
    name: nextcloud-admin-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: virgil
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "nextcloud-main/nextcloud-admin"
