apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-db-secret
  namespace: workload
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-cluster-store
  target:
    name: nextcloud-db-secret
    creationPolicy: Owner
    template:
      data:
        db-name: nextcloud
        db-user: nextcloud
  data:
    - secretKey: db-password
      remoteRef:
        key: nextcloud-initial
        property: nextcloud-db
