platform_nuc_proxmox_host_alias: "platform-nuc"
platform_nuc_template_vm_id: "9000"
platform_nuc_newt_vm_id: "9100"
platform_nuc_worker_vm_id: "9200"

platform_nuc_worker_vm_name: "platform"
platform_nuc_worker_ip_cidr: "192.168.5.182/22"
platform_nuc_worker_gateway: "192.168.4.1"
platform_nuc_worker_bridge: "vmbr0"
platform_nuc_worker_ciuser: "virgil"
platform_nuc_worker_ssh_pubkey_path: "~/.ssh/id_ed25519.pub"
platform_nuc_worker_nameserver: "1.1.1.1"
platform_nuc_worker_cores: "4"
platform_nuc_worker_memory_mb: "4096"
platform_nuc_worker_disk_gb: "64"
