workload_pve_proxmox_host_alias: "workload-pve"
workload_pve_host_ip_cidr: "192.168.6.11/22"
workload_pve_host_gateway: "192.168.4.1"
workload_pve_template_vm_id: "9000"
workload_pve_worker_vm_id: "9300"

workload_pve_worker_vm_name: "workload"
workload_pve_worker_ip_cidr: "192.168.6.181/22"
workload_pve_worker_gateway: "192.168.4.1"
workload_pve_worker_bridge: "vmbr0"
workload_pve_worker_ciuser: "virgil"
workload_pve_worker_ssh_pubkey_path: "~/.ssh/id_ed25519.pub"
workload_pve_worker_nameserver: "192.168.4.1"
workload_pve_worker_cores: "4"
workload_pve_worker_memory_mb: "49152"
workload_pve_worker_disk_gb: "850"
