apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: onepassword-store
  namespace: external-secrets
spec:
  provider:
    onepasswordSDK:
      vault: "5vr4hef2746tpplvjx424xafvu"
      auth:
        serviceAccountSecretRef:
          name: op-token
          key: token
