apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - ../../platform/namespaces
  - ../../platform/sources
  - ../../platform/apps/platform-postgres
  - ../../platform/apps/n8n
  - ../../workload/namespaces
  - ../../workload/sources
  - ../../workload/apps
  - ../../platform/observability
  - ../../platform/backup-state
