config:
  clients:
    - url: http://ops-brain-loki:3100/loki/api/v1/push

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

daemonset:
  enabled: true

tolerations:
  - operator: Exists

extraArgs:
  - -config.expand-env=true
