apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform
configMapGenerator:
  - name: platform-observability-defaults
    files:
      - targets.tsv
generatorOptions:
  disableNameSuffixHash: true
