apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-cluster-store
spec:
  provider:
    onepasswordSDK:
      vault: "5vr4hef2746tpplvjx424xafvu"
      auth:
        serviceAccountSecretRef:
          name: op-token
          namespace: external-secrets
          key: token
