apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-appapi-harp-shared-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-cluster-store
  target:
    name: nextcloud-appapi-harp-shared-key
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        shared-key: "{{ .shared_key }}"
  data:
    - secretKey: shared_key
      remoteRef:
        key: "nextcloud-main/nextcloud-appapi-harp"
